### ISSUE TITLE
in delivery, batch address list submitter doesn't work

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#10]
email from BKelsey sent 2017/02/09:
Regarding the discussion on GitHub, I ran a couple of tests using the new Batch List Submitter. Any thoughts on the results below? Something obvious I’m missing?

Our contact from ICI Society also created their own script which I have attached and tested below (test #5)

GitHub issue:
https://github.com/bcgov/cpf/issues/56

Scripts:
1) https://bcgov.github.io/ols-devkit/als/
2) Client script

Changes:
SERVICE_URL = 'http://test.apps.gov.bc.ca/pub/cpf/ws/'
email = "Brian.Kelsey@gov.bc.ca"
filename = r"H:\temp\atp_addresses_with_address_echo.csv"
localFile = r"H:\temp\TEST_DATA_OUT.csv"
username     = 'addressbc'                                                          
password     = <AS LISTED IN CPF ADMIN>

Results:
1.	LOCAL UNSTRUCTURED FILE – Batch List Submitter

Success – as listed above [Unstructured address list]
Output:
2017/02/09|13:41:24|Sending initial request to: http://test.apps.gov.bc.ca/pub/cpf/ws/apps/geocoder/multiple.json
2017/02/09|13:41:24|Checking status of job 7413 at: http://test.apps.gov.bc.ca/pub/cpf/ws/jobs/7413.json
2017/02/09|13:41:24|Waiting for job to complete (10s)
2017/02/09|13:41:34|Checking status of job 7413 at: http://test.apps.gov.bc.ca/pub/cpf/ws/jobs/7413.json
2017/02/09|13:41:34|Fetching result file url from: http://test.apps.gov.bc.ca/pub/cpf/ws/jobs/7413/results.json
2017/02/09|13:41:35|Fetching job results from: http://test.apps.gov.bc.ca/pub/cpf/ws/jobs/7413/results/1.json
2017/02/09|13:41:35|Processing results from local file: H:\temp\TEST_DATA_OUT.csv
2017/02/09|13:41:35|Average Score: 88.8039215686

2.	URL UNSTRUCTURED FILE – Batch List Submitter

Fail – same as above, but use InputURL
filename =  ‘http://delivery.openmaps.gov.bc.ca/bkelsey/atp_addresses_with_address_echo.csv’

Output: 
2017/02/09|13:46:54|Sending initial request to: http://test.apps.gov.bc.ca/pub/cpf/ws/apps/geocoder/multiple.json
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\pythonwin\pywin\framework\scriptutils.py", line 323, in RunScript
    debugger.run(codeObject, __main__.__dict__, start_stepping=0)
  File "C:\Python27\Lib\site-packages\pythonwin\pywin\debugger\__init__.py", line 60, in run
    _GetCurrentDebugger().run(cmd, globals,locals, start_stepping)
  File "C:\Python27\Lib\site-packages\pythonwin\pywin\debugger\debugger.py", line 654, in run
    exec cmd in globals, locals
  File "H:\CITZ\Geocoder\Client_help\Paul_V\Feb_2017\Batch_List_Submitter_Feb_2017.py", line 4, in <module>
    import sys
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

3.	LOCAL STRUCTURED FILE (Attached) – Batch List Submitter

Fail

Output (attempt #1): 
2017/02/09|13:54:14|Sending initial request to: http://test.apps.gov.bc.ca/pub/cpf/ws/apps/geocoder/multiple.json
2017/02/09|13:54:17|Checking status of job 7417 at: http://test.apps.gov.bc.ca/pub/cpf/ws/jobs/7417.json
2017/02/09|13:54:17|Waiting for job to complete (10s)
2017/02/09|13:54:27|Checking status of job 7417 at: http://test.apps.gov.bc.ca/pub/cpf/ws/jobs/7417.json
2017/02/09|13:54:27|Waiting for job to complete (10s)
2017/02/09|13:54:37|Checking status of job 7417 at: http://test.apps.gov.bc.ca/pub/cpf/ws/jobs/7417.json
2017/02/09|13:54:37|Waiting for job to complete (1s)
2017/02/09|13:54:38|Checking status of job 7417 at: http://test.apps.gov.bc.ca/pub/cpf/ws/jobs/7417.json
2017/02/09|13:54:38|Waiting for job to complete (1s)
2017/02/09|13:54:39|Checking status of job 7417 at: http://test.apps.gov.bc.ca/pub/cpf/ws/jobs/7417.json
2017/02/09|13:54:39|Waiting for job to complete (1s)
2017/02/09|13:54:40|Checking status of job 7417 at: http://test.apps.gov.bc.ca/pub/cpf/ws/jobs/7417.json
2017/02/09|13:54:41|Waiting for job to complete (1s)
2017/02/09|13:54:42|Checking status of job 7417 at: http://test.apps.gov.bc.ca/pub/cpf/ws/jobs/7417.json
2017/02/09|13:54:42|Waiting for job to complete (1s)
2017/02/09|13:54:43|Checking status of job 7417 at: http://test.apps.gov.bc.ca/pub/cpf/ws/jobs/7417.json
2017/02/09|13:54:43|Waiting for job to complete (1s)
2017/02/09|13:54:44|Checking status of job 7417 at: http://test.apps.gov.bc.ca/pub/cpf/ws/jobs/7417.json
2017/02/09|13:54:44|Fetching result file url from: http://test.apps.gov.bc.ca/pub/cpf/ws/jobs/7417/results.json
Geocoding failed on input file.

Output (attempt #2): 
2017/02/09|13:54:56|Sending initial request to: http://test.apps.gov.bc.ca/pub/cpf/ws/apps/geocoder/multiple.json
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\pythonwin\pywin\framework\scriptutils.py", line 323, in RunScript
    debugger.run(codeObject, __main__.__dict__, start_stepping=0)
  File "C:\Python27\Lib\site-packages\pythonwin\pywin\debugger\__init__.py", line 60, in run
    _GetCurrentDebugger().run(cmd, globals,locals, start_stepping)
  File "C:\Python27\Lib\site-packages\pythonwin\pywin\debugger\debugger.py", line 654, in run
    exec cmd in globals, locals
  File "H:\CITZ\Geocoder\Client_help\Paul_V\Feb_2017\Batch_List_Submitter_Feb_2017.py", line 4, in <module>
    import sys
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
>>>

4.	URL STRUCTURED FILE (Attached) – Batch List Submitter
         http://www.cartosmart.com/icis/local/ABBOTSFORD.csv

Fail

Output:
2017/02/09|14:00:20|Sending initial request to: http://test.apps.gov.bc.ca/pub/cpf/ws/apps/geocoder/multiple.json
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\pythonwin\pywin\framework\scriptutils.py", line 323, in RunScript
    debugger.run(codeObject, __main__.__dict__, start_stepping=0)
  File "C:\Python27\Lib\site-packages\pythonwin\pywin\debugger\__init__.py", line 60, in run
    _GetCurrentDebugger().run(cmd, globals,locals, start_stepping)
  File "C:\Python27\Lib\site-packages\pythonwin\pywin\debugger\debugger.py", line 654, in run
    exec cmd in globals, locals
  File "H:\CITZ\Geocoder\Client_help\Paul_V\Feb_2017\Batch_List_Submitter_Feb_2017.py", line 4, in <module>
    import sys
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
>>>

5.	URL STRUCTURED FILE (Attached) – Client script
         http://www.cartosmart.com/icis/local/ABBOTSFORD.csv

<!DOCTYPE html>
<html xml:lang="en">
  <head>
    <title>400 Error</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
    </script>
    <style>
body {
  padding-top: 50px;
}
    </style>
  </head>
  <body>
  <div class="container">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title">400 Error</h3>
      </div>
      <div class="panel-body">

        <h4>I&#039;m sorry the path you requested is not valid.</h4>

        <button type="button" onclick="history.go(-1)" class="btn btn-primary btn-sm"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Back</button>
        <a type="button" href="/pub/cpf/" class="btn btn-primary btn-sm"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home</a>
      </div>
    </div>
  </div>
  </body>
</html>

**Comment by cmhodgson** [comment]
I've committed a new version of the Python code to github:
https://bcgov.github.io/ols-devkit/als/

You can see the changes I made here:
https://github.com/bcgov/ols-devkit/pull/19/commits/03d71a3b4804079ca1163f36dbde88e23ad56221

Paul's suggested method of forcing python to do a multipart/form-data request didn't work for me but I found another way. There are a couple of other changes as well. I was unable to recreate the "Geocoding failed on input file." error from #3 below; if you do have this error again, please provide me with the contents of the url listed just above, in this case:
http://test.apps.gov.bc.ca/pub/cpf/ws/jobs/7417/results.json

That error message suggests that the file at that location doesn't have the structure I am expecting.

Chris

**Comment by mraross** [comment]
on 2017-02-15, Brian Kelsey said:
New Batch List Submitter tested in CPF DLV successfully with the following test cases.
https://bcgov.github.io/ols-devkit/als/

    Local file - Unstructured
    Local file - Structured
    Online file - Unstructured
    Online file - Structured

**Comment by mraross** [comment]
Verified
