### ISSUE TITLE
In betweenPairs demo app, include from/to point counts in calculation status message

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#100]
Change status message from:

BetweenPairs calculated in 1.64 seconds

to:
BetweenPairs took X fromPoints and Y toPoints and calculated X*Y pairs in 1.64 seconds

**Comment by mraross** [comment]
Alternately, just display fromPoint and toPoint counts somewhere in the form and leave the message the betweenPairs calculated message the same.

**Comment by cmhodgson** [comment]
I did both options because it was easy and useful.

**Comment by cmhodgson** [comment]
In delivery (cmhodgson.github.io) now.

**Comment by mraross** [comment]
Now the line connecting the closest point to the start point isn't redrawn when you change the from point.

**Comment by mraross** [comment]
BetweenPairs took 1 fromPoints and 3000 toPoints and calculated 90 pairs in 0.291 seconds. Very impressive. It would have taken 75 minutes in the current betweenPairs, done in groups of 40 to fit within the one minute reverse proxy timeout interval.

**Comment by mraross** [comment]
Verified in test.
