### ISSUE TITLE
Get unexpected error in nearest stop

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#101]
510 Surprise Lake Rd, Atlin, BC
601 Oona River Rd, Oona River, BC
256 McBride Blvd, Atlin, BC
533 Alaska Hwy, Coal River, BC
34396 Babine Lake Rd, Donald Landing, BC

Seems intermittent

**Comment by cmhodgson** [comment]
I cannot duplicate, but of course Oona River is one of those disconnected places so, until we get the new fix  in, it does have the potential to cause trouble in ways we already know and have fixed.

**Comment by cmhodgson** [comment]
This is fixed in delivery now.
https://cmhodgson.github.io/ols-devkit/ols-demo/index.html?env=dlv
