### ISSUE TITLE
In route tab, visually indicate that directions are clickable

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#105]
Visually indicate that one click zoom you to the first intersection of the selected direction and another clicks zoom you back out to the full extent of the route.

**Comment by cmhodgson** [comment]
I'm assuming a mouseover tooltip on the direction, saying "click to zoom to location" or something similar, would suffice?

**Comment by mraross** [comment]
Will the tooltip change when the map is zoomed into a direction? Otherwise, the tooltip should say something like: 
"Click to zoom in to start of route leg or to zoom out to route extent"

**Comment by cmhodgson** [comment]
Yes I would make the content of the tooltip change after clicked and zoomed, to "click to zoom out to route extent" or similar.

**Comment by mraross** [comment]
Perfect.

**Comment by cmhodgson** [comment]
Done locally.
