### ISSUE TITLE
Add ESRI streets and imagery to demo app layer list

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#108]
@mraross commented on [Thu Nov 02 2017](https://github.com/bcgov/api-specs/issues/256)

Sandbox demo available at:
https://gogs.data.gov.bc.ca/leolou/playground/src/master/esri-map-demo.html

Add ESRI streets immediately following MapBox Streets and ESRI imagery immediately following MapBox Satellite

**Comment by cmhodgson** [comment]
Up in delivery now: https://cmhodgson.github.io/ols-devkit/ols-demo/index.html
