### ISSUE TITLE
Not all address finder widget configuration parameters are documented 

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#11]
In address finder widget page in ols dev-kit, localities and notLocalities are not documented. There could be others (e.g.,, matchPrecision, notMatchPrecision, bbox, centre, maxDistance,

**Comment by cmhodgson** [comment]
I added localities, localitiesNot, matchPrecision and notMatchPrecision, the others mentioned (bbos, centre, maxDistance) already exist, and I could find no other missing parameters.

**Comment by mraross** [comment]
Verified
