### ISSUE TITLE
Add a map control that gets the point coordinates under the current map cursor position

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#110]
Add a map control that picks up the coordinates at the cursor location and places them in a special "Add location to route" text box in the Route tab. Once in the text box, there are controls that allow you to add the location to the route ("+") or copy it to the clipboard. There is also a clear text control ("X")

The map control can be as simple as a single click event of the map cursor with no need to select a special map control first.

**Comment by cmhodgson** [comment]
This control will be always available, used by just clicking on the map. (clicking currently has no function)

**Comment by cmhodgson** [comment]
for now, default to civicOnly and excludeUnits

**Comment by mraross** [comment]
The Address in the pop-up could be clickable and, if clicked, it is added to the route.

**Comment by cmhodgson** [comment]
After a phone call with Michael, we decided to skip reverse geocoding (as that is already provided by the site and accessPoint layers) but instead display the coordinates of a clicked-on point, and provide a button to copy them to the clipboard easily, and add also a button to add the location to your route (if the route tab is displayed).

**Comment by cmhodgson** [comment]
I committed and pushed this change to my cmhodgson.github.io fork.
