### ISSUE TITLE
Add a TRIM layer 

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#111]
Exclude grids and contours

**Comment by mraross** [comment]
Here is the geoserver wms request:

``` 
http://openmaps.gov.bc.ca/geo/pub/wms?service=wms&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG:4326&LAYERS=pub:WHSE_BASEMAPPING.TRIM_WATER_LINES,pub:WHSE_BASEMAPPING.TRIM_TRANSPORTATION_LINES,pub:WHSE_BASEMAPPING.DRA_DGTL_ROAD_ATLAS_MPAR_SP,pub:WHSE_BASEMAPPING.TRIM_WATER_POINTS,pub:WHSE_BASEMAPPING.TRIM_TRANSPORTATION_POINTS,pub:WHSE_BASEMAPPING.TRIM_CONTOUR_POINTS&styles=3345,3334,,3344,3333,3332&TRANSPARENT=TRUE&FORMAT=image/png&
```

**Comment by cmhodgson** [comment]
I cannot seem to get anything but an empty (all-transparent) tile back from this service, here is an example url:

http://openmaps.gov.bc.ca/geo/pub/wms?service=WMS&request=GetMap&layers=pub%3AWHSE_BASEMAPPING.TRIM_WATER_LINES%2Cpub%3AWHSE_BASEMAPPING.TRIM_TRANSPORTATION_LINES%2Cpub%3AWHSE_BASEMAPPING.DRA_DGTL_ROAD_ATLAS_MPAR_SP%2Cpub%3AWHSE_BASEMAPPING.TRIM_WATER_POINTS%2Cpub%3AWHSE_BASEMAPPING.TRIM_TRANSPORTATION_POINTS%2Cpub%3AWHSE_BASEMAPPING.TRIM_CONTOUR_POINTS&styles=3345%2C3334%2C%2C3344%2C3333%2C3332&format=image%2Fpng&transparent=true&version=1.1.1&height=256&width=256&srs=EPSG%3A3857&bbox=-13462700.917811524,6339992.874085658,-13384429.400847504,6418264.391049678

**Comment by mraross** [comment]
Verified in test.
