### ISSUE TITLE
In business name tag, clear icon doesn't work

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#113]
Entered the following occupant: 
KSDavison & Associates, UNIT 207 -- 225 Francis Way, New Westminster, BC
then clicked on clear icon. Text box didn't clear.

**Comment by mraross** [comment]
Text box clear function works in prod.

**Comment by cmhodgson** [comment]
Fixed in delivery now. Also I changed the example text for the businesses by tag  tab to the shortest example of a multi-word tag I could find, "first nations".
