### ISSUE TITLE
Update Geocoder API URLs

### ISSUE THREAD

**Issue by cmhodgson** [bcgov/ols-devkit#124]
It seems that the previous urls:
https://(delivery|test).apps.gov.bc.ca/pub/geocoder/
no longer work and should perhaps be updated to:
https://(geocoderdlv|geocodertst).api.gov.bc.ca/

**Comment by cmhodgson** [comment]
Should the prod api also be updated from:
https://apps.gov.bc.ca/pub/geocoder/
to:
https://geocoder.api.gov.bc.ca/
?

Can/should all of these changes be made live now?

**Comment by cmhodgson** [comment]
Changes made, committed, PR'd, and approved.

**Comment by mraross** [comment]
Verified in test.
