### ISSUE TITLE
in address finder widget demo, display coordinates in a form suitable for copy/paste into other mapping frameworks 

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#13]

**Comment by cmhodgson** [comment]
Can you please clarify what this means, specifically.

**Comment by cmhodgson** [comment]
Still waiting for an explanation of what this specifically means. What other mapping frameworks? What exactly would you copy and paste?

**Comment by mraross** [comment]
Display coordinates in lat,lon sequence so they can be copied and pasted into google maps/earth, bing, etc.

**Comment by cmhodgson** [comment]
I changed "Longitude: X, Latitude: Y" into "Latitude,Longitude: Y,X" for the simple example's sample output.

**Comment by mraross** [comment]
Verified
