### ISSUE TITLE
Update ESRI plugin for leaflet

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#133]
Newer plugin supports going down past level 18 in a layer

**Comment by cmhodgson** [comment]
ESRI supports level 19, google and mapbox streets and imagery layers both support going down to level 20. If the map allows you to go down to 20, and you have the esri layers on, they just disappear when you do the last zoom... do you want the map to only zoom to 19, or go to 20 for those other layers?

**Comment by cmhodgson** [comment]
You can see what happens with the map maxZoom set to 20 here: http://office.refractions.net/~chodgson/gc/ols-demo/index.html

**Comment by cmhodgson** [comment]
This is committed to my github.

**Comment by mraross** [comment]
Verified in test
