### ISSUE TITLE
Update Parcels layer to point to ParcelMap BC 

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#134]
Change WMS layer to:
https://openmaps.gov.bc.ca/geo/pub/WHSE_CADASTRE.PMBC_PARCEL_FABRIC_POLY_SVW/ows?service=WMS&request=GetCapabilities

and change layer name in legend from Parcels to ParcelMap BC

**Comment by cmhodgson** [comment]
Done locally, visible here:
http://office.refractions.net/~chodgson/gc/ols-demo/index.html?env=tst

**Comment by cmhodgson** [comment]
Fixed the Layer name to now read ParcelMap BC as well.

**Comment by cmhodgson** [comment]
Committed to my github, now in pull request.

**Comment by mraross** [comment]
Verified in test
