### ISSUE TITLE
in address finder and occupant finder widgets, turn off chrome autocomplete

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#145]
Sometimes, when you start entering an address, Chrome's native autocomplete takes over instead of the geocoder autocomplete.

**Comment by mraross** [comment]
Here is a possible solution from:
https://stackoverflow.com/questions/50604671/programmatically-disabling-chrome-auto-fill


At this time (May, 2019) only autocomplete="new-password" is working well.

It can do programmatically with jQuery for example :

$('form, input, select').attr('autocomplete', 'new-password');

**Comment by cmhodgson** [comment]
autocomplete="new-password" on the input element doesn't work, in  chrome, as of now... but setting autocomplete="off" on the FORM element the wraps the input, does work. This is done now.

**Comment by mraross** [comment]
Verified in test
