### ISSUE TITLE
Control route styling from setting of Truck Mode, not Follow truck route

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#151]
Currently, when you select Truck Mode and enter a height, weight, length, or width restriction, the resulting route is not partitioned into truck/non-truck route segments. Only when you select follow truck route does the resulting route get partitioned. Its useful to see truck/non-truck route partitioning when you are fiddling with any truck setting, not just follow truck route.

**Comment by cmhodgson** [comment]
Done. Live on refractions dev site.

**Comment by mraross** [comment]
Verified in test
