### ISSUE TITLE
Update location services in action app as needed to test new translink features

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#152]
@mraross commented on [Fri Mar 13 2020](https://github.com/bcgov/ols-router/issues/234)

1. Best route partitioning
2. Global distortion fields
3. Local distortion fields
4. Intersection Crossing costs
5. Turn costs
6. Enable features
7. Directional weight restrictions

**Comment by mraross** [comment]
We need to be able to tweak costs to tune it for realism!
xing costs include yield, stop sign, traffic light times and intersection crossing time factor.
turn costs include left ,right, and straight turn costs.
local and global distortion field friction costs.

**Comment by cmhodgson** [comment]
Local Distortion fields will not be tweakable through the UI. The UI for all of the other features is now available on https://office.refractions.net/~chodgson/gc/ols-demo/?rt=rri and I have deployed a new build supporting these UI features.

**Comment by cmhodgson** [comment]
The UI includes a magic input field called "The One String" which contains all of the config values in one string. You can push a button beside to copy to your clipboard. To later apply all the same config you just triple-click to highlight everything in the field, press backspace to confirm you selected and cleared the entire field, then paste in your previously copied string and press enter or click on another field.

**Comment by mraross** [comment]
Works like a charm. Thanks Chris.

**Comment by mraross** [comment]
Chris, one minor issue: Can you please change the name of the magic input field in the UI from: 
    The One String

to
     Tuning String

**Comment by cmhodgson** [comment]
Ha. OK. done.

**Comment by cmhodgson** [comment]
Also added validation to the fields so they will highlight in red if there is not a valid number in them. most of them are set to accept values in the range 0.1 - 100 which I think should be broad enough but might also catch some typos etc.

**Comment by mraross** [comment]
Super, thanks. Will try it out right now.

**Comment by mraross** [comment]
Verified in test
