### ISSUE TITLE
In Demo app, MapBox Streets has disappeared

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#165]
When you start up demo app, there is no map and Mapbox Streets is the default map layer. Mapbox Satellite still works so I don't think its a subscription issue.

**Comment by mraross** [comment]
To confirm fix, visit:

https://ols-demo.apps.gov.bc.ca/index.html

and you should see the mapbox street layer:

![image](https://user-images.githubusercontent.com/11318574/93504931-055b2700-f8cf-11ea-8967-3d12284c5c2a.png)

**Comment by cmhodgson** [comment]
I believe this is done and should be closed now.

**Comment by mraross** [comment]
Verified in test
