### ISSUE TITLE
In demo app, autocompletion and random jump stopped working

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#168]
Try entering address in Route tab or Business name tab
Try random jump in route tab.

Failed to load resource: the server responded with a status of 404 ()
leaflet.js:5 Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. Error
    at y (https://unpkg.com/leaflet@1.2.0/dist/leaflet.js:5:2048)
    at Function.v.extend (https://unpkg.com/leaflet@1.2.0/dist/leaflet.js:5:14706)
    at https://bcgov.github.io/ols-devkit/ols-demo/leaflet-layerjson.js:4:30
    at https://bcgov.github.io/ols-devkit/ols-demo/leaflet-layerjson.js:390:4
y @ leaflet.js:5
Sortable.js:1 Failed to load resource: the server responded with a status of 404 ()
index.html:2084 Uncaught ReferenceError: Sortable is not defined
    at index.html:2084

**Comment by cmhodgson** [comment]
This was already fixed and delivered in PR #169. I think it should be marked as done.

**Comment by mraross** [comment]
Verified in test
