### ISSUE TITLE
Add a Occupants Nearby widget that supports tag autocompletion

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#17]
Create a javascript widget that requests an HTML5 Geolocation from the user's browser, asks for a list of tags, with autocompletion on input, then issues a geocoder/occupants/near request.

    Find nearest occupant or occupants nearby

    Tags:___________________

    [Find nearest] [Find nearby]
        uses geolocation tag to get user's lat/lon
        tags will autocomplete
        number of results returned by Find nearby controlled by config parameter maxResults

**Comment by mraross** [comment]
Look at example 4 in the following:
https://sean.is/poppin/tags

taggle clearly uses substring matching without regard for position in the tag string. This adds a lot of noise to a simple lookup. I would prefer if we limited searching to beginnings of words (e.g., "ma" should match "applied mathematics" but not "information"

**Comment by cmhodgson** [comment]
This was implemented within the DataBC Location services demo app #14

**Comment by mraross** [comment]
Verified
