### ISSUE TITLE
In demo app, Address tab, add a list of examples under the address text box

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#174]
Displaying a list of address examples below the address input text box is one way to teach users how to enter sitenames. To understand why sitenames are now important in geocoder 4.1, see [here](https://github.com/bcgov/ols-geocoder/issues/154)

Include the word Examples as follows:

      Examples: 
         1175 Douglas St Victoria BC
         201A 1175 Douglas St Victoria BC
         Victoria BC
         Douglas St and Yates St Victoria BC
         Delta Port Entrance -- Roberts Bank Rd Delta BC 
         Delta Creek Bridge --  Terrace BC
         Boston Bar 8 -- Boston Bar BC
         Brentwood Bay -- Central Saanich BC
         Fairfield -- Victoria BC
         Hwy 1 and Exit 366

**Comment by mraross** [comment]
@cmhodgson I originally posted the following incorrect example:

     Delta Port Terminal Entrance -- Roberts Bank Rd Delta BC

It should be:

     Delta Port Entrance -- Roberts Bank Rd Delta BC

Please correct the demo app

**Comment by cmhodgson** [comment]
Done.

**Comment by mraross** [comment]
Please update the following examples to reflect the change in handling non-DRA localities

     Boston Bar 8 near Boston Bar BC
     Brentwood Bay in Central Saanich BC
     Fairfield in Victoria BC

**Comment by cmhodgson** [comment]
Done, committed to my github for testing.

**Comment by mraross** [comment]
Verified in test
