### ISSUE TITLE
in demo app, add support for a url parameter that excludes street-level matches from geocoder results

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#175]
Adding support for a noStreets parameter will allow developers to see the effect of excluding street-level matches leaves more meaningful address choices. Currently, if you enter West Van into Geocoder 4.0, you will get the following matches:

     West Boulevard, Vancouver, BC
     East Boulevard, Vancouver, BC
     West Port Overpass, West Vancouver, BC
     rest area, West Vancouver, BC
     West Grant Channel Pit-Lake, Indian Arm, BC

If you exclude street-level matches, you get the following:

     West Vancouver, BC
     North Vancouver, BC
     Bowen Island, BC
     Vancouver, BC
     Lions Bay, BC

Unfortunately, you don't get District of North Vancouver (it is the sixth match) but the list is much more relevent.

If noStreets  is present in demo app URL, then exclude street-level matches from results in Address tab. If time permits update Route tab as well.

https://office.refractions.net/~chodgson/gc/ols-demo/?gc=rri&noStreets

If noStreets has to have a value, make it a boolean as in:

https://office.refractions.net/~chodgson/gc/ols-demo/?gc=rri&noStreets=true

**Comment by cmhodgson** [comment]
Done:
https://office.refractions.net/~chodgson/gc/ols-demo/?gc=rri&noStreets

**Comment by mraross** [comment]
Verified in test
