### ISSUE TITLE
In demo app, address tab, add a View as List icon that returns a list of geocoder results in an HTML page

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#176]
For QA and training purposes, add an icon called "View as List" that starts up another browser tab, issues a GET request against the address resource and returns an HTML list of results. The request could be the same one made by the autocompletion widget except the format is HTML instead of json.  The icon should appear between the View in Google Maps and Clear icons.

During geocoder QA,its currently awkward and time-consuming to pull up the web browser developer tools, copy the link address, paste it into a new tab, and change the format to html to see address match details such as score, matchPrecision, and faults. Now that we should the element value in each fault, and need to fine tune the scoring system, the View as List icon will save a lot of effort during geocoder 4.1 UAT.

The View as List icon would also be useful in app developer and power-user training materials.

**Comment by cmhodgson** [comment]
I modified the view as list function to link to the .xhtml output which includes a stylesheet that outlines the tables making it easier to understand the output.

**Comment by cmhodgson** [comment]
This is now committed to my repo and viewable at eg. https://cmhodgson.github.io/ols-devkit/ols-demo/?gc=rri

**Comment by mraross** [comment]
Verified in test.
