### ISSUE TITLE
Add an occupant finder widget that supports name/address autocompletion

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#18]
The widget expects the user to enter an occupant name unless a front gate delimeter is entered or the matchPrecision parameter is set to something other than occupant.

    The widget UI should look like this:

    Name:_________________________

    [Find]

    Add a tags parameter to the widget to allow developers to filter results by tags.

The occupant finder widget should be a simple extension of the address finder widget.

**Comment by cmhodgson** [comment]
This was implemented within the DataBC Location services demo app #14

**Comment by mraross** [comment]
Verified
