### ISSUE TITLE
In demo app, address tab, display admin areas with every geocoded address  

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#189]
Demonstrate to developers how to use the geocoder to find admin areas for a civic address by displaying the CHSA of last geocoded address in the left panel, below the Examples. Here is a possible layout:

\<last geocoded address\> is in the following admin areas:
CHSA: <\some-community-health-service-area\>

All the above admin areas are returned with a single WFS request as follows:
https://openmaps.gov.bc.ca/geo/pub/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=pub%3AWHSE_ADMIN_BOUNDARIES.BCHA_CMNTY_HEALTH_SERV_AREA_SP&srsname=EPSG:4326&cql_filter=INTERSECTS(SHAPE,POINT(1195413.0%20382453.0))&propertyName=CMNTY_HLTH_SERV_AREA_NAME,LOCAL_HLTH_AREA_NAME,HLTH_SERVICE_DLVR_AREA_NAME,HLTH_AUTHORITY_NAME&outputFormat=application%2Fjson

**Comment by mraross** [comment]
Display LHA, CSDA, and HA using results of a single request to the CHSA feature in the WFS. We have confirmed with the custodian that all admin area names and codes in the CHSA record are current and accurate.

LOCAL_HLTH_AREA_CODE, LOCAL_HLTH_AREA_NAME, HLTH_SERVICE_DLVR_AREA_CODE, HLTH_SERVICE_DLVR_AREA_NAME, HLTH_AUTHORITY_CODE, HLTH_AUTHORITY_NAME

**Comment by cmhodgson** [comment]
This has been completed, PR'd and merged now.

**Comment by mraross** [comment]
Verified in test
