### ISSUE TITLE
ALE: Score and Precision value locations in result

### ISSUE THREAD

**Issue by BK01** [bcgov/ols-devkit#201]
The address list editor interface as well as CSV export are showing the score values under the precision field, and the precision values under the score field.

For example, the JS file below shows the 'SCORE_VAL' as corresponding to column #4..
https://github.com/bcgov/ols-devkit/blob/gh-pages/ale/js/ale.js

..which has a 'precision' heading in the GUI and CSV export.
https://bcgov.github.io/ols-devkit/ale/

**Comment by cmhodgson** [comment]
Apparently I accidentally re-ordered those column headings when I did the changes to support CHSA:
https://github.com/bcgov/ols-devkit/commit/60b897d3bb5acf837d440a6b60abd7a6b30a22ff#diff-aa4da491efd2718f275549bbdb7d47aeb7381cfbe08ff06f6ed5cf3cbc94793f

Here is a PR to fix it:
https://github.com/bcgov/ols-devkit/pull/202
