### ISSUE TITLE
Pseudo street  and locality aliases cause confusion in autocompletion tools

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#30]
In the addresses tab of the location services demo, when you enter partial names like Black Rd, you get a match of Black Rd as an alias of Black Creek Rd. This is very confusing because when you look on the map at the addresses on Black Rd, Black Creek BC, they all have a streetName of Black Creek Rd, not Black Rd. In fact, all five matches are partial name street aliases.

It would be less confusing if all pseudo-street aliases such as Black Rd, Black Creek, BC could be eliminated from the match results.

**Comment by cmhodgson** [comment]
I think this is going to be handled on the server side by: https://github.com/bcgov/api-specs/issues/176

**Comment by mraross** [comment]
Verified
