### ISSUE TITLE
In address tab, trigger address display as soon as an address is selected 

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#31]
In address tab, when you select an address from the list of candidates, you need to press the search icon to get the address displayed on the map. It would be simpler if the address was displayed on the map as soon as you select it from the list. If you want to edit the address in some way, you can do that then hit the search button.

**Comment by mraross** [comment]
In address tab:
1. Enter bushby st then pick bushby st victoria bc from list. Map zooms to correct location.
2. Delete victoria bc then pick bushby st new westminster from list. Map doesn't zoom to correct location.

**Comment by cmhodgson** [comment]
Actually, there is no order of operations required to demonstrate this - no matter what you pick from the list, it always picks the first one, regardless of whether it is the second time picking from the list or the first. Fixed in my fork now.

**Comment by mraross** [comment]
Verified
