### ISSUE TITLE
Make shortest and fastest route layers very transparent

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#36]
This allows the user an unobstructed view of the shortest route or the road under the routes.

**Comment by cmhodgson** [comment]
Alternatively or additionally we could make the routes transparent with 50% alpha or so.

**Comment by mraross** [comment]
I don't think transparency will help distinguish red from grey when they are on top of each other but is otherwise useful.  So, I think we still need route layer controls but transparency is a good addition

**Comment by cmhodgson** [comment]
The DRA road layer uses red for highways, and grey doesn't stand out well when transparent. I' trying pinky-purple and blue as the new colors, with 50% opacity.

**Comment by mraross** [comment]
verified in fork

**Comment by mraross** [comment]
Verified
