### ISSUE TITLE
Update geocoder requests to include new brief and autocomplete parameters

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#39]
brief=true will return a minimum of attributes.
autocomplete=true informs the geocoder that addressString contains a partial address that should be autocompleted. This will enable partial word and partial name completion for both street and locality name s.

Geocoder requests in both address and route requests should be updated.

**Comment by cmhodgson** [comment]
autocomplete=true is now in place for the autocomplete functions of the geocoder, router, and occupants by name. Brief=true is in place for all of those as well as the full geocode search and occupant by name search, and the occupants, sites, and intersections layers.

**Comment by cmhodgson** [comment]
In Delivery now.

**Comment by mraross** [comment]
Verified
