### ISSUE TITLE
Link each route direction to the appropriate intersection

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#42]
This allows a user to see the detailed geometry of each leg in the journey. Requires enhancement to route/directions resource to include intersection point with each direction.

**Comment by cmhodgson** [comment]
When do we display the point on the map? I assume, when a user mouses-over a direction?

**Comment by cmhodgson** [comment]
click direction to zoom to intersection. highlight selected direction blue to match intersection highlight circle. click again to zoom to full route view, or click a different direction to pan/zoom to it and highlight it.

**Comment by cmhodgson** [comment]
Implemented.

**Comment by cmhodgson** [comment]
In Delivery now.

**Comment by mraross** [comment]
Very nice. Does leave a blue circle on map after route stops deleted.

**Comment by cmhodgson** [comment]
Fixed locally now.

**Comment by cmhodgson** [comment]
Fix is in delivery.

**Comment by mraross** [comment]
Verified in delivery
