### ISSUE TITLE
Add a DRA layer to layers list

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#45]
Add a BC Digital Road Atlas layer to the layers list. It should be sourced from GeoServer and appear immediately after Parcels in the layer list. This will come in handy when the imagery base is selected and when comparing OSM streets to the DRA.

**Comment by cmhodgson** [comment]
Please provide the service endpoint URL and layer name.

**Comment by mraross** [comment]
http://openmaps.gov.bc.ca/geo/ows?service=wms&version=1.3.0&request=GetCapabilities

layer name is pub:WHSE_BASEMAPPING.DRA_DGTL_ROAD_ATLAS_MPAR_SP

**Comment by mraross** [comment]
Verified in fork

**Comment by mraross** [comment]
Verified
