### ISSUE TITLE
In route tab, add support for multiple stops and stop order optimization

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#46]
The route planner app should have the following interface:
Input fields:
A fixed number of stops (e.g., 5) that lets you enter addresses into.
A Number of random points field that lets you enter a number between 1 and maxAllowedRoutePoints (default of 10).

Function buttons:

[Find Route] [Find Optimal Route] [Find Optimal Random Route]

Find Route finds shortest and fastest route that visits the fixed number of stops in given order.
Find Optimal Route finds shortest and fastest route that visits the fixed number of stops in an optimal order.
Find Optimal Random Route finds the fastest route that visits a number of randomly chosen stops in an optimal order.

When Find Optimal Route is pressed, do the following:
1. Use betweenPairs to get distances between stops in the route. Use same points in To and From parameters.
2.  Make a request to the optimal-route resource which will return a list of nodes in optimal order.
3. To get a displayable route, request a route from the route planner for stops in the order given by optimal-route.

When Find Optimal Random Route is pressed, do the following:
1. Pick the requested number of points at random from within the current mapview.
2. Do the steps for Find Optimal Route

**Comment by mraross** [comment]
When displaying results in panel, add a button for shortest and fastest routes. When clicked, it loads the appropriate directions and zooms the map to the extent of the route. Putting shortest and fastest route buttons here localizes the extent controls with the route function and obviating the need to add them to the map controls.

**Comment by mraross** [comment]
In addition to search and clear icons for each start/stop in route, add a Surprise Me icon/button (*) in between Search and Clear icons. When the Surprise Me icon is pressed, do the following:

1. Add a random offset to the current map centre location
2. Fold the coordinates back into the province if necessary
3. Find the nearest site to the random location
4. Populate input text box with site address and display address location on the map

**Comment by mraross** [comment]
The title of the app should be _**BC Route Planner in Action**_

**Comment by mraross** [comment]
Update way demo app handles disconnected route points.
Add clickable direction legs that zoom the map to the first intersection in the leg.

**Comment by cmhodgson** [comment]
Note: The route planner app will not directly make use of betweenPairs, betweenPairs is called internally within /optimal/route

**Comment by cmhodgson** [comment]
This functionality has been incorporated into the Location Services in Action App, no separate router app required at this time.

**Comment by mraross** [comment]
verified
