### ISSUE TITLE
Add geographical names to map layers sourced from BCGNWS

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#55]
Add the following layers to map layers using the BCGNWS:
```
Populated Place Names
Geographical Names
```
Include only official names
Set maxFeatures=200 for all layers
By default, these layers should not be visible
Placemark should be labelled with geoname
Use a circular placemark icon

**Comment by cmhodgson** [comment]
It is not clear to me that it is possible to write a single query to combine populated places with Indian Reserves? But I think I can still combine the two layers into one visible layer in leaflet.

**Comment by mraross** [comment]
Right you are, so second layer should be all geographical names

**Comment by mraross** [comment]
The scale of the geographical names layer should be lower than that of the populated places layer which needs no scale limit.

**Comment by mraross** [comment]
Only need one layer: geographical names (e.g., all geonames)

**Comment by cmhodgson** [comment]
I don't know how dense that layer is but I'm concerned that leaflet has no map-labeling/label placement algorithm so text will just be placed on top of each other, looking pretty poor. Is there a WMS server for the BCGNWS names that will sort this out for me?

**Comment by cmhodgson** [comment]
Or we might be able to use clustering to solve the label collision problem, if it really is a problem.

**Comment by mraross** [comment]
Let's not worry about label collisions and see what it looks like. When you get down below 134 eye altitude, most labels sort themselves out.

**Comment by mraross** [comment]
We could have a pop-up for each name with same info as in physical address viewer. This could help disambiguate overlapping labels.

**Comment by mraross** [comment]
Have a look at this geonames WMS layer:

https://openmaps.gov.bc.ca/geo/pub/WHSE_BASEMAPPING.GNS_GEOGRAPHICAL_NAMES_SP/ows?service=WMS&request=GetCapabilities

**Comment by cmhodgson** [comment]
In delivery now.

**Comment by mraross** [comment]
Verified
