### ISSUE TITLE
in location services demo app, occupant found in places by tag can't be found in places by name

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#56]
In location services demo app, the following occupant is found in Places by tag (e.g., courts) but not in Places by name:

PRINCE RUPERT LAW COURTS -- 100 Market Pl, Prince Rupert, BC

**Comment by mraross** [comment]
Civic address exists:
https://delivery.apps.gov.bc.ca/pub/geocoder/addresses.json?addressString=100%20Market%20Pl%2C%20Prince%20Rupert%2C%20BC&locationDescriptor=any&maxResults=1&interpolation=adaptive&echo=true&outputSRS=4326&minScore=1&provinceCode=BC

**Comment by cmhodgson** [comment]
The answer can be founder here: https://delivery.apps.gov.bc.ca/pub/geocoder/occupants/addresses.xhtml?minScore=50&maxResults=10&addressString=PRINCE+RUPERT+LAW+COURTS--

Which is the query that the auto-completer is running but with a larger maxResults - the matches that are show in the auto-complete have higher scores because they are non-civic sites, so there is no penalty for a missing street address. because the law courts have a civic number, there is a penalty for missing it, and so it comes out with a lower score.

**Comment by mraross** [comment]
This works:
https://delivery.apps.gov.bc.ca/pub/geocoder/occupants/addresses.xml?addressString=PRINCE%20RUPERT%20LAW%20COURTS%20--%20100%20Market%20Pl%2C%20Prince%20Rupert%2C%20BC&matchPrecision=OCCUPANT

This doesn't ( the law courts isn't the top match):
https://delivery.apps.gov.bc.ca/pub/geocoder/occupants/addresses.xml?addressString=PRINCE%20RUPERT%20LAW%20COURTS%20--&matchPrecision=OCCUPANT

**Comment by mraross** [comment]
In the places by name tab, if I enter the following:
PRINCE RUPERT LAW COURTS -- 100 Market Pl, Prince Rupert, BC

I still don't get it in the results. Why is that? Could it be the way you handle the front gate?

**Comment by cmhodgson** [comment]
It works for me... if I look at the network traffic in the developer tools, it shows:

https://apps.gov.bc.ca/pub/geocoder/occupants/addresses.json?addressString=PRINCE+RUPERT+LAW+COURTS+--+100+Market+Pl%2C+Prince+Rupert%2C+BC

which also works as expected.

**Comment by mraross** [comment]
The demo app works with prod data but not test data (test=true)

**Comment by cmhodgson** [comment]
After some discussion, Michael and Chris propose to add two new faults, CIVIC_ADDRESS.missing and NON_CIVIC_ADDRESS.missing, for cases where only the name is input (nothing after '--'). These two faults should have the same penalty (probably between 10 and 12), and should replace any street name, locality, and province missing faults.

**Comment by cmhodgson** [comment]
This requires a back-end fix which is here: bcgov/api-specs#199

**Comment by cmhodgson** [comment]
The back-end fix mentioned above does fix this issue.

**Comment by mraross** [comment]
Verified in test.
