### ISSUE TITLE
Remove scale restriction on businesses map layer

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#68]
Just return up to maxResults results.

**Comment by cmhodgson** [comment]
This is done but not yet testable as we have no live occupant data.

**Comment by mraross** [comment]
Try STN 309 ANAHIM LAKE -- 6637 Marten Rd, Anahim Lake, BC

**Comment by cmhodgson** [comment]
Something else is preventing occupants from being displayed at lower zoom levels (eg. full province view) but some occupants do display at some (but not all) lower zoom levels. Further investigation forthcoming...

**Comment by cmhodgson** [comment]
It appears that the failure is being caused by some small number of occupants not having a valid business category in the current data. If any such occupants are within the bbox, the display fails. There are no such problems against 3.2 with the latest data.

**Comment by cmhodgson** [comment]
This is working in delivery now.

**Comment by mraross** [comment]
Verified
