### ISSUE TITLE
Set autocomplete=false when search button is pressed in address and business name tabs

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#70]
set autocomplete=true only while user types into input text box.

**Comment by cmhodgson** [comment]
Good idea. Lets you still access scoring etc. when appropriate.

**Comment by cmhodgson** [comment]
Autocomplete is only set to true for the auto-completion requests, the search requests do not set autocomplete (it defaults to false).

**Comment by cmhodgson** [comment]
Done and in Delivery now.

**Comment by mraross** [comment]
Verified
