### ISSUE TITLE
Add occupant business details to pop-up in business searches

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#71]
Add the following fields:

imageUrl - display image or No image text
occupantDescription - title Description
websiteUrl - title Website
contactEmail - Contact email
contactPhone - Contact phone
contactFax - Contact fax
keywords   
businessCategoryClass - title Category
naicsCode - title NAICS Code

**Comment by cmhodgson** [comment]
occupant details added.

**Comment by mraross** [comment]
a long keyword list exceeds the balloon dimensions instead of being wrapped around to the next line.

**Comment by cmhodgson** [comment]
I've added <wbr> after semi-colons in the keyword list and after slashes in the website url to give word-break suggestions to the browser and this seems to solve the problem nicely.

**Comment by mraross** [comment]
Verified
