### ISSUE TITLE
Add support for a starting point parameter in the location services app url

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#75]
Allow a user to open the locations services app with the map centred on a given point as in:

https://ols-demo.apps.gov.bc.ca/index.html?point=50.734739,-127.500669

**Comment by mraross** [comment]
Treat the starting point as a point input to the geocoder text box. In other words, allow a point as an alternative to an address in the geocoder text box.

**Comment by cmhodgson** [comment]
We could call this parameter something other than "point", as it also accepts an addressString (basically it just takes whatever is there and sticks it in the geocoder input field and geocodes it).

**Comment by cmhodgson** [comment]
google calls it this parameter "q"...

**Comment by cmhodgson** [comment]
This is done and in delivery.

**Comment by mraross** [comment]
Verified
