### ISSUE TITLE
in route tab, add a Random Address icon to Route start and end fields (after search icon)

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#77]
In Route tab, add a Random Address icon that, when pressed, generates a random point within the current bbox then returns the nearest address to it.
The icon for Random Address could be a dice.

**Comment by cmhodgson** [comment]
Use bootstrap asterisk icon.

**Comment by cmhodgson** [comment]
Added to address tab as well.

**Comment by cmhodgson** [comment]
This needs to be limited to return only CAPs, as NCAPs are often too far from the road to route to, and are not useful for comparing against google. See bcgov/api-specs#222 for how I'd like to do this.

**Comment by mraross** [comment]
Add excludeUnits=true to ensure apartment buildings with multiple units don't get overrepresented

**Comment by mraross** [comment]
Here's a way to improve the random address walk so it never gets stuck or contains consecutive duplicate addresses. It could generate loops of two or more addresses which is acceptable.

If address input field is empty
    pick an address at random from within current map view
    if there are no addresses in current map view
       pick an address at random from the N nearest addresses
            to the map view centre point
    endif

else
    pick an address at random from the nearest N addresses
endif

We have to play a bit to determine a decent value for N.
For bonus points, make N an application parameter called &neighbour

**Comment by mraross** [comment]
To avoid getting stuck, don't change map level when centering on random address.

**Comment by cmhodgson** [comment]
This is in delivery now with slight modifications based on our discussions.

**Comment by mraross** [comment]
Verified
