### ISSUE TITLE
in route tab, add a view in google maps icon to start and end route point fields

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#78]
Add an icon to view address/point in google maps. This will allow users to compare Physical Address Geocoder location to Google Maps location

If start/end field contains an address, button action should link to:
   http://maps.google.com/?q=address 

If start/end field contains lat/lon coordinates, button action should link to:
http://maps.google.com/?q=lat,lon

**Comment by cmhodgson** [comment]
Also added to geocoder input field. Because we are getting a lot of buttons, and it is eating up the length of the input fields, I narrowed the buttons by reducing the left and right padding a bit.

**Comment by cmhodgson** [comment]
Done in delivery.

**Comment by mraross** [comment]
Verified that View in google maps icon removed from Route tab to simply UI.
