### ISSUE TITLE
In route tab, a previous route is sometimes left on the map when a new route is displayed 

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#81]
Pick a random start point around the greater victoria area.
Repeatedly pick a random end point.
Eventually, you will get a previous route left on the map. I have had multiple previous routes left on the map after about thirty random end points.  It appears to have something to do with random points that are near the boundary of the map view.

**Comment by cmhodgson** [comment]
This is fixed in the new version now on my cmhodgson github. Not to do with the location of the random points, just clicking random faster that the route loads causes a race condition between the multiple loading routes.

**Comment by mraross** [comment]
Verified
