### ISSUE TITLE
In route tab, add a Nearest Stop option

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#86]
When nearest stop is selected, system issues a betweenPairs request with fromPoints= first route point and toPoints=all route points except the first. Nearest Stop takes precedence over Optimize.

**Comment by cmhodgson** [comment]
I imagine the betweenPairs request would also include a topRouteCount=1 - note that a second request would the be required to calculate the actual route as betweenPairs only returns the distance and time. Or we could add routeBetweenPairs and DirectionsBetweenPairs, probably a bit overwhelming amount of output unless topRouteCount is used and relatively small (1 to 3?).

I would make the Nearest Stop and Optimize buttons automatically toggle the other off if they are toggled on - like radio buttons except with a none of the above option implied by un-selecting the currently selected one.

**Comment by mraross** [comment]
I prefer just doing two requests in the demo app with the betweenPairs request using topRouteCount=1 as you suggest.  Making Nearest Stop and Optimize mutually exclusive is ideal. Please proceed.

**Comment by cmhodgson** [comment]
This is implemented now. Nearest Stop is also mutually exclusive with Round Trip. One question is how to label the route points, right now they are labelled in the same way as an non-optimized route.

**Comment by mraross** [comment]
That labelling sounds fine.

**Comment by cmhodgson** [comment]
In delivery now.

**Comment by mraross** [comment]
Verified in test.
