### ISSUE TITLE
Minor changes to map layers list

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#87]
Based on feedback from MOTI, realized that users need to know locationDescriptor of Addresses layer to do a meaningful comparison with Google Maps and both Addresses layers needed to be together to more clearly demonstrate that DataBC Geocoder has two location types and Google Maps only one.

Change layer name from Addresses to Addresses - parcel point
Move layer named Addresses - access point to immediately follow Addresses - parcel point

**Comment by cmhodgson** [comment]
Done. (still need to commit to github with other changes)

**Comment by cmhodgson** [comment]
In delivery now.

**Comment by mraross** [comment]
Verified
