### ISSUE TITLE
Timed out route requests not handled properly

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#88]
Get javascript error dialogue on request timeout. Can this error be handled more meaningfully?

https://routerdlv.api.gov.bc.ca/directions.json?apikey=11dd756f680c47b5aef5093d95543738&criteria=fastest&roundTrip=false&points=-123.3404867%2C48.4200157%2C-125.9100423%2C49.1546349

HTTP/1.1 200 OK
Date: Wed, 09 Aug 2017 05:06:11 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Server: Apache-Coyote/1.1
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Security-Policy: script-src 'self' 'unsafe-eval'
Access-Control-Allow-Origin: https://cmhodgson.github.io
Access-Control-Allow-Credentials: true
X-Kong-Upstream-Latency: 391
X-Kong-Proxy-Latency: 0

**Comment by cmhodgson** [comment]
There are a lot of reasons why a request might not get a valid response, one of them is a timeout, another might be a server outage or network issue. It is not always easy or possible to identify the specific cause. I'm presently handling all request failures with a generic failure javascript alert, basically The demo app is making the assumption that the backend should respond, and such errors should be rare (I haven't experienced a timeout in my testing). I'm guessing if google's servers didn't respond to a request from the google maps UI, that it would cause a similarly generic error message, or just a flat out failure in the UI. 

How do you know it is a timeout error? (that URL works fine for me in a short time). How would you like this to be handled?

**Comment by cmhodgson** [comment]
I have improved the error messages in the javascript alerts to be more descriptive, indicating that there was an unexpected server problem and that the user should try again.

**Comment by cmhodgson** [comment]
In delivery now.

**Comment by mraross** [comment]
Verified in test.
