### ISSUE TITLE
Wrong behavior for non-existent route

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#91]
The following route points:

150 Rolston Island, Kyuquot, BC
1028 Princess Ave, Victoria, BC
1577 McRae Ave, Saanich, BC

Yield the following message instead of no such route.

Route travels 999999999 km in 277777 hours 46 minutes
Directions:

**Comment by cmhodgson** [comment]
Yup, this fix didn't make it into that release, it is done now.

**Comment by cmhodgson** [comment]
In delivery now.

**Comment by mraross** [comment]
Verified in test.
