### ISSUE TITLE
in address tab, jump at random icon stopped transmitting requests to geocoder

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#92]
I turned on Chrome network monitor and no request was sent to geocoder when I pressed jump-at-random icon. This happened after I entered a few addresses in Victoria and Metchosin and pressed jump and view in GM icons a few times.

A workaround is to click the X icon then hit * again. Seems that icon state is getting lost somehow.

**Comment by cmhodgson** [comment]
I've already found and fixed this one locally since the last delivery.

**Comment by cmhodgson** [comment]
In delivery now.

**Comment by mraross** [comment]
Verified in test.
