### ISSUE TITLE
in route tab, When jump at random is selected, address isn't displayed before route calculation is started

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#95]
This is most notable with a route that takes a long time to calculate (e.g., a dozen points and optimize order selected). So, if it you have 12 addresses and you change one of them by selecting jump at random, the old address is still visible for the seven or so seconds it takes to calculate the optimal order. In the meantime, it just looks like Jump at Random didn't work because the address didn't change before the route starting calculating.

**Comment by cmhodgson** [comment]
I cannot duplicate this and there is no reason for it to behave this way. I find that the address changes and the point moves nearly instantly, then the sidebar is update to say "calculating route" and then the wait for the route occurs. Routing cannot proceed until the point is updated, which happens at the same time as the address being updated.

**Comment by mraross** [comment]
There is a fair amount of delay after jump at random is pressed and before Calculating route message is displayed. How about a Preparing route points message before executing Jump at Random action?

**Comment by cmhodgson** [comment]
Done Locally.

**Comment by cmhodgson** [comment]
in delivery now.

**Comment by mraross** [comment]
Verified in test
