### ISSUE TITLE
In Route table, display time to calculate distances between stops

### ISSUE THREAD

**Issue by mraross** [bcgov/ols-devkit#96]
After route is calculated, display an additional message showing time it took to calculate distances between stops.  So the route tab should look something like this after route calculation is finished:

Distances between stops calculated in X seconds
Route calculated in Y seconds
Route travels D km in T seconds

**Comment by cmhodgson** [comment]
BetweenPairs is run on the server, internally, as part of an "optimizedRoute" call. I don't know how long it takes to do the distance matrix until after the entire call is complete. There are ways that I could report this back while the call is still in progress but would require major changes on the servers side and would likely confuse clients other than our own app. 

If you want to see all of the information about the time taken to do the work, there are actually 3 numbers that add up to the total executionTime:
- betweenPairs distance calculation (reported as routingExecutionTime)
- optimal route determination (reported as optimizationExecutionTime)
- final route calculation (time can be calculated as the total executionTime less the two times above)

**Comment by cmhodgson** [comment]
Here is the text I've come up with:

Distances between stops calculated in 1.866 seconds
Optimization performed in 0.141 seconds
Final route calculated in 0.294 seconds
Route travels 1535.419 km in 25 hours 41 minutes

**Comment by cmhodgson** [comment]
Done locally.

**Comment by mraross** [comment]
Verified in test
